name: Verify and Deploy

on:
  pull_request:
    branches:
      - main
      - development
  push:
    branches:
      - main
      - development

jobs:
  verify:
    name: Verify Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Build Application
        run: npm run build

      - name: Install API Dependencies
        run: |
          cd api
          npm install --production
          cd -

  deploy:
    name: Deploy to Azure Static Web Apps
    runs-on: ubuntu-latest
    needs: verify
    if: github.event_name == 'push' && (github.ref_name == 'main' || github.ref_name == 'development')

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Debug GitHub Ref
        run: "echo 'GitHub Ref: ${{ github.ref }}'"

      - name: Set Deployment Environment
        id: set-env
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "ENVIRONMENT=Production" >> $GITHUB_ENV
          elif [[ "${{ github.ref_name }}" == "development" ]]; then
            echo "ENVIRONMENT=Development" >> $GITHUB_ENV
          else
            echo "ENVIRONMENT=Unknown" >> $GITHUB_ENV
          fi

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "src"
          api_location: "api"
          output_location: "dist/bhagavad-gita"
