name: Verify and Deploy

on:
  pull_request:
    branches:
      - main
      - development
  push:
    branches:
      - main
      - development

jobs:
  verify_and_deploy:
    name: Verify and Deploy
    runs-on: ubuntu-latest

    env:
      AZURE_STATIC_WEB_APPS_API_TOKEN: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
      APP_LOCATION: "src"
      OUTPUT_LOCATION: "dist/bhagavad-gita"

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Step 3: Set Deployment Environment
      - name: Set Deployment Environment
        run: |
          if [ "${{ github.event_name }}" == "push" ]; then
            if [ "${{ github.ref_name }}" == "main" ]; then
              echo "SWA_CLI_DEPLOY_ENV=Production" >> $GITHUB_ENV
            else 
              echo "SWA_CLI_DEPLOY_ENV=development" >> $GITHUB_ENV
            fi
          elif [ "${{ github.event_name }}" == "pull_request" ]; then
            if [ "${{ github.base_ref }}" == "main" ]; then
              echo "SWA_CLI_DEPLOY_ENV=Production" >> $GITHUB_ENV
            else
              echo "SWA_CLI_DEPLOY_ENV=development" >> $GITHUB_ENV
            fi
          fi

      # Step 4: Install dependencies
      - name: Install Dependencies
        run: npm install

      # Step 5: Install Angular CLI
      - name: Install Angular CLI
        run: npm install -g @angular/cli

      # Step 6: Build the application
      - name: Build Application
        run: npm run build

      # Step 7: Install API dependencies
      - name: Install API Dependencies
        run: |
          cd api
          npm install --production
          cd -

      # Debug Step: Print Event Info
      - name: Debug Event Info
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Base Ref: ${{ github.base_ref }}"
          echo "Ref Name: ${{ github.ref_name }}"
          echo "Deployment Environment: $DEPLOYMENT_ENVIRONMENT"

      # Step 8: Conditionally deploy to Azure Static Web Apps
      - name: Deploy to Azure Static Web Apps
        if: >
          (github.event_name == 'pull_request' && github.base_ref == 'development') ||
          (github.event_name == 'push' && github.ref == 'refs/heads/main')
        env:
          DEPLOYMENT_ENVIRONMENT: ${{ env.DEPLOYMENT_ENVIRONMENT }}
        run: |
          npx @azure/static-web-apps-cli deploy \
            --app-location ${{ env.APP_LOCATION }} \
            --api-location api \
            --output-location ${{ env.OUTPUT_LOCATION }} \
            --deployment-token ${{ env.AZURE_STATIC_WEB_APPS_API_TOKEN }} \
            --api-language node \
            --api-version 20
